plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - user_docs
  - deployment
  - developer_docs
title: Circa
theme: jekyll-theme-midnight
